version: '3.3'
services:
    web:
       restart: always
       build: .
       command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn micro_printing_service.wsgi:application --bind 0.0.0.0:8000"
       volumes:
           - .:/var/www/
       ports:
         - "8000:8000"
    
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 80
          - 443
        ports:
          - "80:80"
          - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web
