# Generated by Django 3.0.6 on 2020-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photos',
            field=models.ImageField(upload_to='photos/%d/', verbose_name='Фотография'),
        ),
    ]
